#!/usr/bin/env bash

# 10/03/2021

# shellcheck disable=SC2034
BLACK="\u001b[30m"
RED="\u001b[1;31m"
GREEN="\u001b[1;32m"
YELLOW="\u001b[1;33m"
BLUE="\u001b[34m"
MAGENTA="\u001b[35m"
CYAN="\u001b[36m"
WHITE="\u001b[37m"
RESET="\u001b[0m"

_menu() {
arg=$1
echo -e "${arg}"
echo -e '-ssh\t\t\t\t| Setting up the ssh key.'
echo -e '-github-nopass or -github\t| Github push without password on project.'
echo -e "${RESET}"
}
# Start felib
felib_installed() {
arg=$1
if [ -x "$(command -v "$arg")" ]; then
return 1
else
return 0
fi
}

felib_file_exists() {
arg=$1
if [ -f "$arg" ]; then
return 1
else
return 0
fi
}

felib_dir_exists() {
arg=$1
if [ -d "$arg" ]; then
return 1
else
return 0
fi
}
# Start general_cmd
general_cmd_github() {
echo "Type the username."
read -r USERNAME
echo "Type the password."
read -r PASSWORD
echo "Type the repository name."
read -r REPONAME
git config remote.origin.url https://"${USERNAME}":"${PASSWORD}"@github.com/"${USERNAME}"/"${REPONAME}".git
}

general_cmd_ssh() {
DIR="$HOME/.ssh/"
FILE="$HOME/.ssh/id_ed25519.pub"
if [ -d "$DIR" ] && [ -f "$FILE" ]; then
echo "You already have an SSH key Here it is:"
echo ""
cat "$HOME"/.ssh/id_ed25519.pub
exit 0
elif [ -d "$DIR" ] && [ ! -f "$FILE" ]; then
echo "You do have the folder but not the ssh file 'id_ed25519.pub"
echo " "
echo "Type Your Email "
read -r EMAIL
echo "Is this your email address correct? [y/n] : $EMAIL"
read -r right
if [[ $right == "y" ]]; then
ssh-keygen -t ed25519 -C "$EMAIL"
echo " "
echo "This is your SSH Key."
cat ~/.ssh/id_ed25519.pub
fi
exit 0
else
echo "You don't have a ssh key. Lets Create one"
echo "Type Your Email "
read -r EMAIL
echo "Is this your email address correct? [y/n] : $EMAIL"
read -r right
if [[ $right == "y" ]]; then
ssh-keygen -t ed25519 -C "$EMAIL"
echo " "
echo "This is your SSH Key."
cat ~/.ssh/id_ed25519.pub
fi
fi
}
# Start the main
while [[ "$1" ]]; do
case "$1" in
-ssh)
general_cmd_ssh
exit 0
;;

-github-nopass | -github)
# general_cmd
general_cmd_github
exit 0
;;

-help | -man | man)
_menu "$YELLOW"
exit 0
;;

*)
_menu "$RED"
exit 0
;;

esac
done

if [[ -z "${1}" ]]; then
_menu "$GREEN"
fi
